import { NavBar, Footer } from "../../components/layout/";
import "../../styles/globals.css";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=" 
        border-2 border-green-700">
        <NavBar/ >
        <div className="pt-20">{children}</div>
        <Footer />
      </body>
    </html>
  )
}
