import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

import Dashboard from "../../components/admin/layout/Dashboard";

import "../../styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex">
        <SidebarProvider>
          <div>
            <Dashboard />
          </div>
          <div className="flex-1">
            <SidebarTrigger />
            {children}
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
